name: Metrics (Linguagens privadas + colaboração)

on:
  schedule: [{ cron: "0 6 * * *" }]  # roda todo dia às 06:00 UTC (03:00 em São Paulo)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necessário para commitar o SVG no repositório
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # o secret que você criou
          user: alexandrecardos0

          # arquivo de saída que vamos usar no README
          filename: assets/metrics.languages.svg

          # apenas o bloco de linguagens
          base: ""

          # === LINGUAGENS ===
          plugin_languages: yes
          plugin_languages_indepth: yes      # análise mais precisa
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css

          # incluir privados e afiliações (dono, colaborador e membro de org)
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no
