name: Metrics (Linguagens privadas + colaboração)

on:
  schedule:
    - cron: "0 6 * * *"   # roda todo dia às 06:00 UTC (03:00 em São Paulo)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # precisa escrever o SVG no repositório
    steps:
      - name: Generate languages metrics
        uses: lowlighter/metrics@latest
        with:
          # --- Autenticação ---
          token: ${{ secrets.METRICS_TOKEN }}   # PAT classic salvo como secret
          user: alexandrecardos0
          config_timezone: America/Sao_Paulo

          # --- Saída ---
          filename: assets/metrics.languages.svg

          # --- Layout base (sem outros cards) ---
          base: ""
          template: classic

          # --- LINGUAGENS ---
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage   # mostra %
          plugin_languages_categories: programming, markup    # foca front + PHP
          plugin_languages_limit: 8
          plugin_languages_threshold: "2%"                    # esconde < 2%

          # --- Escopo de repositórios (inclui privados e colaboração) ---
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no
